#=================================================
# Description: Build ubports using GitHub Actions
# Lisence: MIT
# Contributor: 0312birdzhang
# Maintainer: Danct12
# Credit: https://github.com/P3TERX/Actions-OpenWrt
#=================================================

name: Build System Image

on: 
  push:
    branches:
      - master
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-20.04

    env:
      VENDOR: xiaomi
      DEVICE: santoni
      ANDROID_ROOT: /home/runner/halium/

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo dpkg --add-architecture i386
        sudo apt install git gnupg flex bison gperf build-essential \
        zip bzr curl libc6-dev x11proto-core-dev \
        libgl1-mesa-dev g++-multilib mingw-w64-i686-dev tofrodos \
        python3-markdown libxml2-utils xsltproc schedtool \
        liblz4-tool bc lzop imagemagick libncurses5 rsync \
        python-is-python3 python2
        git config --global user.name "UBports Redmi 4X CI"
        git config --global user.email "thisemaildoesnotexist@exist.com"

    - name: Downloading source code
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+rx ~/bin/repo
        mkdir -p ~/bin
        echo export PATH=\$PATH:\$HOME/bin >> ~/.bashrc
        source ~/.bashrc
        export PATH=$PATH:~/bin
        mkdir ~/halium && cd ~/halium
        repo init -u https://github.com/Halium/android -b halium-7.1 --depth=1
        repo sync -c -j 16
        bash halium/devices/setup santoni
    
    - name: Downloading source code
      run: |
        source halium.env
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        repo init -u https://github.com/Halium/android -b halium-7.1 --depth=1
        mkdir -p $ANDROID_ROOT/.repo/local_manifests
        wget https://raw.githubusercontent.com/ubports-santoni/halium-devices/halium-7.1/manifests/"$VENDOR"_"$DEVICE".xml -O $ANDROID_ROOT/.repo/local_manifests/$DEVICE.xml
        repo sync -j8 -c --no-clone-bundle --no-tags
    
    - name: Build HAL
      run: |
        chmod +x build-hal.sh
        bash -x build-hal.sh
      shell: bash

    - name : Upload boot image
      uses: actions/upload-artifact@master
      with:
        name: halium-boot image
        path: /home/runner/work/halium/out/target/product/santoni/halium-boot.img

    - name : Upload recovery image
      uses: actions/upload-artifact@master
      with:
        name: Recovery image
        path: /home/runner/work/halium/out/target/product/santoni/recovery.img

    - name : Upload system image
      uses: actions/upload-artifact@master
      with:
        name: System image
        path: /home/runner/work/halium/out/target/product/santoni/system.img
